[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""

  hostname = ""
  omit_hostname = false

# --------------------------------------------------
# Prometheus endpoint
# --------------------------------------------------

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"

# --------------------------------------------------
# System metrics
# --------------------------------------------------

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  report_active = true

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = [
    "tmpfs",
    "devtmpfs",
    "devfs",
    "overlay",
    "squashfs"
  ]

[[inputs.diskio]]

[[inputs.net]]

[[inputs.netstat]]

[[inputs.processes]]

[[inputs.system]]