{
 "title": "System Metrics for the Linux Hosts",
 "description": "Monitoring Linux Hosts via telegraf agent.",
 "tags": [
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_uptime, ident)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(disk_used_percent{fstype!=\"rootfs\", ident=\"$instance\"}, device)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{ident=\"$instance\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_up{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{ident=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "received by the {{interface}}"
    },
    {
     "expr": "rate(net_bytes_sent{instance=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "sent by the {{interface}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{ident=\"$instance\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{ident=\"$instance\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{ident=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_system{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{ident=\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load5{ident=\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load15{ident=\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{ident=\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "processes_dead{ident=\"$instance\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "processes_idle{ident=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "processes_paging{ident=\"$instance\"}",
     "legendFormat": "Paging"
    },
    {
     "expr": "processes_running{ident=\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "processes_sleeping{ident=\"$instance\"}",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "processes_stopped{ident=\"$instance\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "processes_unknown{ident=\"$instance\"}",
     "legendFormat": "Unknown"
    },
    {
     "expr": "processes_zombies{ident=\"$instance\"}",
     "legendFormat": "Zombies"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{ident=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{ident=~\"$instance\"}",
     "legendFormat": "mem_used"
    },
    {
     "expr": "mem_buffered{ident=~\"$instance\"}",
     "legendFormat": "mem_buffered"
    },
    {
     "expr": "mem_cached{ident=~\"$instance\"}",
     "legendFormat": "mem_cached"
    },
    {
     "expr": "swap_used{ident=~\"$instance\"}",
     "legendFormat": "mem_swap"
    },
    {
     "expr": "mem_free{ident=\"$instance\"}",
     "legendFormat": "mem_free"
    }
   ]
  },
  { "title": "Block devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disks Usages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{ident=~\"$instance\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{ident=~\"$instance\",name!~\"dm-[0-9]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{ident=~\"$instance\",name!~\"dm-[0-9]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(diskio_io_time{ident=\"$instance\"}[1m])/10",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}